name: Build and deploy Node.js app to Azure Web App - cms-by-puck-editor-v3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        working-directory: ./ui

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./ui  # Adjust this path to upload the built artifacts correctly

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./ui  # Adjust this path to download the built artifacts correctly
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BE919FE6F3AA42C1A5E1643AB7E5E170 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ADFDD0205119486E807C1CED3C11D0B3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3EB68EBF63AD49AF9EA61683CDAA12E3 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'cms-by-puck-editor-v3'
          slot-name: 'Production'
          package: ./ui  # Adjust this path to point to the correct package location
